'use client';

import React from 'react';
import CitationBadge from './CitationBadge';
import { Citation } from '@/lib/api';

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  citations?: Citation[];
  provider_used?: string;
  isStreaming?: boolean;
}

export default function MessageBubble({ message }: { message: Message }) {
  const isUser = message.role === 'user';

  const renderContent = () => {
    if (isUser) return message.content;

    const parts = message.content.split(/(\[\d+\])/g);

    return parts.map((part, index) => {
      const match = part.match(/\[(\d+)\]/);
      if (match && message.citations) {
        const markerNum = parseInt(match[1], 10);
        const citation = message.citations.find(c => c.marker === markerNum);
        if (citation) {
          return <CitationBadge key={index} citation={citation} marker={`[${markerNum}]`} />;
        }
      }
      return <span key={index}>{part}</span>;
    });
  };

  return (
    <div className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div
        className={`max-w-[85%] md:max-w-[75%] rounded-2xl p-4 shadow-sm
          ${isUser
            ? 'bg-blue-600 text-white rounded-br-none'
            : 'bg-white border border-slate-200 text-slate-800 rounded-bl-none'
          }`}
      >
        <div className="whitespace-pre-wrap leading-relaxed text-[15px]">
          {renderContent()}
          {message.isStreaming && (
            <span className="inline-block w-2 h-4 ml-1 bg-slate-400 animate-pulse align-middle" />
          )}
        </div>
        {message.provider_used && (
          <div className="mt-3 text-xs text-slate-400 border-t border-slate-100 pt-2">
            Generated by {message.provider_used}
          </div>
        )}
      </div>
    </div>
  );
}
